title: "Welcome"

connections:
    - title: "DigitalOcean"
      server: "mydroplet.example.net"
      username: root
      port: 4022
      shortcut: d
    - title: "Home Server"
      server: "192.168.1.5"
      port: 4022
      username: johndoe
      shortcut: k
